[profile.default]
solc_version = "0.8.18"

src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

optimizer = true
optimezer_runs = 1000
# match_path = "test/unit/*"
# via_ir = true
# ffi = true
evm_version = 'paris'

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
ethereum = "${ETHEREUM_RPC_URL}"
moonbase = "${MOONBASE_RPC_URL}"
linea_goerli = "${LINEA_GOERLI_RPC_URL}"
linea = "${LINEA_RPC_URL}"
lumx = "${LUMX_RPC_URL}"
besu = "${BESU_RPC_URL}"
besuAfo = "${BESU_RPC_AFO}"
bitcoin = "${BITCOIN_RPC_URL}"
bvm = "${BVM_RPC_URL}"
whitebit = "${WHITEBIT_RPC_URL}"
nostest = "${NOSTEST_RPC_URL}"
nos = "${NOS_RPC_URL}"

[etherscan]
linea = { key = "${LINEA_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
mumbai = { url = "https://api-testnet.polygonscan.com/api", key = "${POLYGONSCAN_API_KEY}" }
polygon = { url = "https://api.polygonscan.com/api", key = "${POLYGONSCAN_API_KEY}" }
ethereum = { key = "${ETHERSCAN_API_KEY}" }
moonbase = { url = "https://api-moonbase.moonscan.io/api", key = "${MOONSCAN_API_KEY}" }
lumx = { url = "https://evmexplorer.tanssi-chains.network?rpcUrl=https://fraa-dancebox-3082-rpc.a.dancebox.tanssi.network", key = "${ETHERSCAN_API_KEY}" }


[invariant]
runs = 500
depth = 200
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
